### ISSUE TITLE
Could not run some of the STK functions

### ISSUE THREAD

**Issue by bkaangorur** [stk-kriging/stk#21]
Hello all,

When I want to run some of the STK functions (e.g. stk_sampling_randomlhs(2, [2 3; 4 5])), I encounter with the following error:
`error: octave_base_value::function_value(): wrong type argument '<unknown type>'`

As well, when I run stk_example_kb03 function, it only draws top-left plot and then crashes with the above error.

I use a clean installation of Octave 6.1.0-w64 portable version in 64-bit Windows 7. I installed STK from the .tar.gz file. I am able to run those functions without any problem  in Octave 4.4.1.

Btw, should I run anything after installing/loading STK package manually? I'm asking this, because I noticed that there is a STK related script, namely `stk-post-install.m`, in `OCTAVE_HOME/mingw64/share/octave/site/m/once_only`.

I will be appreciated if you can help me.

Thanks in advance.

**Comment by jbect** [comment]
Hello.

1) Unfortunately Octave 6.1 contains several bugs (regressions) that render STK completely unusable.  This is a know issue that has been fixed since then (see https://savannah.gnu.org/bugs/?func=detailitem&item_id=59340).

2) The Octave installer for windows comes with STK pre-installed.  Which means that you should not have to install anything, just type `pkg load stk` from the Octave prompt and STK should be ready to use.

3) If for some reason you really need to install / update STK "manually", then you can do very easily it using `pkg install -forge stk`.  You don't even need to download the tarball, Octave does it for you.

I suggest that you install a fresh copy of Octave 6.2.0, released a few days ago, and then try option 2).

HTH,
Julien

**Comment by bkaangorur** [comment]
Actually, I tried to loaded pre-installed STK package firstly, as you have said. When it does not work, I tried to install STK manually, and it did not work, neither.

Btw, I debugged the STK and realized that the error occurs in stk_rescale function. At first sight, I supposed that it is a recursive function, but probably it is not. Apparently, Octave cannot call @stk_hrect/stk_rescale function. (To be honest I could not understand how Octave can distinguish that function from the stk_rescale function in arrays/generic/stk_rescale.m)

I will also try to run it in Octave 6.2.0, and update this post.

**Comment by jbect** [comment]
Don't even try to understand the problem.  It's something internal to Octave.  It's supposed to be fixed in 6.2.0.

**Comment by bkaangorur** [comment]
It works without any problem in 6.2.0. Thank you very much.

**Comment by jbect** [comment]
:relieved:
